apiVersion: v1
kind: Secret
metadata:
  name: fcg-orders-secret
  namespace: default
type: Opaque
stringData:
  # JWT Secret Key
  Jwt__Key: ${JWT_SECRET_KEY}

  # Database Connection String (Full)
  ConnectionStrings__FCGOrdersDbConnection: "${DB_CONN_ORDERS}"

  # Service Bus Connection String
  ServiceBus__ConnectionString: ${SERVICEBUS_CONNECTION_STRING}
